# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_auto_20170628_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokers', models.ManyToManyField(related_name='allpokes', to='logreg.User')),
            ],
        ),
    ]
