# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0006_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='pokers',
        ),
        migrations.AddField(
            model_name='poke',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poke',
            name='poked',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='poked_user', to='logreg.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='poking_user', to='logreg.User'),
            preserve_default=False,
        ),
    ]
