# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0008_auto_20170629_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptFriend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepter', to='logreg.User')),
                ('friendRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='logreg.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
